const { _electron: electron } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, '.test-data', `smoke-${Date.now()}`);
fs.mkdirSync(dataDir, { recursive: true });
fs.mkdirSync(path.join(root, 'artifacts'), { recursive: true });
const waveFile = path.join(dataDir, 'local-tone.wav');
const wav = Buffer.alloc(44 + 16000 * 2);
wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(16000, 24); wav.writeUInt32LE(32000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(32000, 40);
for (let i = 0; i < 16000; i++) wav.writeInt16LE(Math.round(1500 * Math.sin(2 * Math.PI * 220 * i / 16000)), 44 + i * 2);
fs.writeFileSync(waveFile, wav);
fs.writeFileSync(path.join(dataDir, 'state.json'), JSON.stringify({ position: { x: 300, y: 250 }, timer: { mode: 'focus', remaining: 1800 }, settings: { chime: false, musicPath: waveFile } }));

async function findPage(app, filename) {
  await app.firstWindow();
  const deadline = Date.now() + 10000;
  while (Date.now() < deadline) {
    const page = app.windows().find(p => p.url().endsWith(filename));
    if (page) return page;
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  throw new Error(`Window did not load: ${filename}`);
}

(async () => {
  const errors = [];
  let app;
  try {
    const env = { ...process.env, MORI_DATA_DIR: dataDir };
    for (const key of Object.keys(env)) if (key.toUpperCase() === 'ELECTRON_RUN_AS_NODE') delete env[key];
    const launchOptions = process.env.SMOKE_PACKAGED ? { executablePath: path.join(root, 'dist', process.env.SMOKE_SIDE_BY_SIDE ? `Mori Focus ${require('../package.json').version}` : 'Mori Focus', 'Mori.exe'), args: [], env } : { args: [root], env };
    app = await electron.launch(launchOptions);
    app.on('window', page => page.on('pageerror', e => errors.push(e.message)));
    const pet = await findPage(app, 'pet.html');
    await pet.waitForSelector('#pet');
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.ready === 'true', null, { timeout: 8000 });
    assert.equal(await pet.locator('#pet').getAttribute('data-reading-ready'), 'true');
    await pet.evaluate(async () => {
      const { PetSprite } = await import('./pet-sprite.mjs');
      const canvas = document.createElement('canvas'); canvas.width = 440; canvas.height = 380;
      const sprite = new PetSprite(canvas);
      const pixels = () => canvas.toDataURL();
      const check = (condition, message) => { if (!condition) throw new Error(message); };
      await sprite.load('assets/mori-catgirl-atlas.png');
      sprite.draw('read', 1000, { reducedMotion: true }); const fallback = pixels();
      sprite.draw('readBlink', 1000, { reducedMotion: true });
      check(pixels() === fallback, 'missing expression must preserve original reading pose');
      await sprite.loadReading('assets/mori-reading-atlas.png');
      sprite.family = ''; sprite.draw('crouch', 1000, { calm: true }); const crouch = pixels();
      sprite.draw('idle', 1100, { calm: true }); sprite.draw('read', 1200, { calm: true });
      check(pixels() === crouch, 'standing to reading uses the crouch transition');
      sprite.draw('read', 1500, { calm: true }); const reading = pixels();
      check(reading !== crouch, 'transition must finish in reading pose');
      sprite.draw('idle', 1600, { reducedMotion: true }); sprite.draw('read', 1700, { reducedMotion: true });
      check(pixels() === reading, 'reduced motion skips crouch transition');
      sprite.draw('readHappy', 1700, { calm: true });
      check(pixels() !== reading && pixels() !== crouch, 'seated reaction uses its own expression without a standing transition');
    });
    await pet.emulateMedia({ reducedMotion: 'reduce' });
    await app.evaluate(({ ipcMain }) => { globalThis.lastMoriHit = null; ipcMain.on('hit-test', (_event, hit) => { globalThis.lastMoriHit = hit; }); });
    await pet.mouse.move(22, 65);
    await pet.waitForTimeout(100);
    assert.equal(await app.evaluate(() => globalThis.lastMoriHit), false, 'transparent sprite margin must pass through clicks');
    await pet.mouse.click(120, 145);
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'readHappy');
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isVisible()), false, 'single click greets without opening the panel');
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'read');
    await pet.screenshot({ path: path.join(root, 'artifacts', 'catgirl-reading.png'), omitBackground: true });
    await pet.mouse.move(120, 90);
    await pet.mouse.move(136, 83, { steps: 3 });
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'readHappy');
    await pet.screenshot({ path: path.join(root, 'artifacts', 'catgirl-happy.png'), omitBackground: true });
    await pet.mouse.move(120, 145);
    await pet.mouse.down();
    await pet.mouse.move(145, 150, { steps: 4 });
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'held');
    await pet.screenshot({ path: path.join(root, 'artifacts', 'catgirl-held.png'), omitBackground: true });
    await pet.mouse.up();
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose !== 'held');
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isVisible()), false, 'dropping never opens tools');
    await pet.evaluate(() => document.querySelector('#pet').addEventListener('pointerdown', event => { window.testPointerId = event.pointerId; }, { once: true }));
    await pet.mouse.move(120, 145); await pet.mouse.down(); await pet.mouse.move(145, 150, { steps: 3 });
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'held');
    await pet.evaluate(() => document.querySelector('#pet').dispatchEvent(new PointerEvent('pointercancel', { pointerId: window.testPointerId })));
    await pet.mouse.up();
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose !== 'held');
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isVisible()), false, 'canceling a drag does not open tools or leave the held pose');
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'read');
    await pet.mouse.dblclick(167, 188);
    await pet.waitForTimeout(150);
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isVisible()), true, 'double-clicking the tail opens the actual tool window even though greeting changes the silhouette');
    const panel = await findPage(app, 'panel.html');
    await panel.waitForSelector('#start');
    await panel.evaluate(async () => { await window.mori.act('companionSettings', { key: 'guideSeen', value: true }); document.querySelector('#guide-dialog')?.close(); });
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isAlwaysOnTop()), false, 'tools default to a normal floating window');
    await panel.locator('#pin-panel').click();
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isAlwaysOnTop()), true);
    await panel.locator('#pin-panel').click();
    await panel.locator('#task-input').fill('整理今天的靈感');
    await panel.locator('#task-form button').click();
    await panel.locator('.task-title').first().waitFor();
    await panel.locator('.task-title').first().click();
    await panel.locator('#start').click();
    await panel.waitForFunction(() => document.querySelector('#mode-break').getAttribute('aria-pressed') === 'true');
    assert.equal(await panel.locator('#rounds').textContent(), '1');
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'readHappy');
    assert.equal(await panel.locator('#memories .unlocked').count(), 1);
    await panel.locator('#presence').selectOption('quiet');
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('pet.html')).isVisible()), false);
    await panel.evaluate(() => window.mori.windowAction('hide'));
    await panel.evaluate(() => window.mori.windowAction('hide'));
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isVisible()), true, 'quiet visibility toggle opens settings for explicit mode changes');
    assert.equal((await panel.evaluate(() => window.mori.getState())).settings.presence, 'quiet', 'shortcut does not silently disable do-not-disturb');
    await panel.locator('#presence').selectOption('focus');
    await panel.locator('#mode-focus').click();
    await panel.waitForFunction(() => document.querySelector('#mode-focus').getAttribute('aria-pressed') === 'true');
    await panel.locator('#start').click();
    await panel.waitForFunction(() => document.querySelector('#start span').textContent === '暫停一下');
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'read');
    await pet.emulateMedia({ reducedMotion: 'no-preference' });
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'readBlink', null, { timeout: 12000 });
    await pet.screenshot({ path: path.join(root, 'artifacts', 'catgirl-reading-blink.png'), omitBackground: true });
    await pet.waitForFunction(() => document.querySelector('#pet').dataset.pose === 'read');
    await pet.emulateMedia({ reducedMotion: 'reduce' });
    await pet.mouse.move(1, 1);
    await pet.waitForFunction(() => document.querySelector('#bubble').hidden);
    await panel.locator('#presence').selectOption('quiet');
    assert.equal((await panel.evaluate(() => window.mori.getState())).timer.running, true, 'quiet mode does not pause focus');
    await panel.locator('#presence').selectOption('companion');
    await pet.mouse.move(1, 1);
    await pet.waitForFunction(() => document.querySelector('#bubble').hidden);
    await pet.mouse.move(120, 145);
    await pet.waitForTimeout(120);
    assert.equal(await pet.locator('#bubble').isVisible(), false, 'passing over the character does not immediately show a bubble');
    await pet.waitForFunction(() => !document.querySelector('#bubble').hidden);
    await pet.mouse.move(1, 1);
    await panel.locator('#sound-settings summary').click();
    const tracks = [];
    for (const [source, title] of [['reading', '書頁之間'], ['forest', '森林散步'], ['night', '深夜小燈'], ['station', '微光車站'], ['seaside', '海鹽假日'], ['garden', '月下庭院']]) {
      await panel.locator('#music-source').selectOption(source);
      await panel.locator('#music-toggle').click();
      await panel.waitForFunction(() => document.querySelector('#music-toggle').getAttribute('aria-pressed') === 'true');
      assert.equal(await panel.locator('#music-title').textContent(), title);
      const metrics = await panel.evaluate(() => {
        const buffer = audio.musicNode.buffer;
        let energy = 0, peak = 0;
        for (let c = 0; c < buffer.numberOfChannels; c++) for (const value of buffer.getChannelData(c)) { energy += value * value; peak = Math.max(peak, Math.abs(value)); }
        return { duration: buffer.duration, rms: Math.sqrt(energy / (buffer.length * buffer.numberOfChannels)), peak, first: buffer.getChannelData(0)[0], last: buffer.getChannelData(0).at(-1), loop: audio.musicNode.loop, source: audio.trackSource };
      });
      assert.ok(metrics.duration > 20 && metrics.rms > 0 && metrics.rms <= 0.101 && metrics.peak <= 0.851);
      assert.equal(Math.abs(metrics.first), 0); assert.equal(Math.abs(metrics.last), 0);
      assert.equal(metrics.loop, true); assert.equal(metrics.source, source);
      tracks.push({ title, ...metrics });
      await panel.waitForTimeout(500);
      assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).webContents.isCurrentlyAudible()), true);
      await panel.locator('#music-toggle').click();
    }
    fs.writeFileSync(path.join(root, 'artifacts', process.env.SMOKE_PACKAGED ? 'packaged-music-results.json' : 'music-results.json'), JSON.stringify(tracks, null, 2));
    await panel.locator('#music-source').selectOption('cafe');
    await panel.locator('#music-toggle').click();
    await panel.waitForFunction(() => document.querySelector('#music-toggle').getAttribute('aria-pressed') === 'true');
    assert.equal(await panel.locator('#music-title').textContent(), '貓咪咖啡館');
    assert.equal(await panel.evaluate(() => audio.musicNode.buffer.duration), 151);
    assert.equal(await panel.evaluate(() => audio.musicNode.loop), true);
    await panel.locator('#rain-toggle').click();
    await panel.waitForFunction(() => document.querySelector('#rain-toggle').getAttribute('aria-pressed') === 'true');
    await panel.evaluate(() => { window.testMusicNode = audio.musicNode; });
    for (const source of ['brown', 'pink', 'ocean']) {
      await panel.locator('#background-source').selectOption(source);
      await panel.waitForFunction(expected => audio.backgroundSource === expected && Boolean(audio.rainNode), source);
      assert.equal(await panel.evaluate(() => audio.rainNode.buffer.duration), 32);
      assert.equal(await panel.evaluate(() => audio.rainNode.loop), true);
      assert.equal(await panel.evaluate(() => audio.musicNode === window.testMusicNode), true, 'background changes must not restart music');
    }
    await panel.waitForFunction(() => document.querySelector('#toast').hidden);
    await panel.screenshot({ path: path.join(root, 'artifacts', 'panel.png') });
    await panel.locator('#sound-settings summary').click();
    await panel.evaluate(() => { document.querySelector('.panel-content').scrollTop = 0; });
    await panel.screenshot({ path: path.join(root, 'artifacts', 'companion-panel.png') });
    await panel.locator('#finish-day').scrollIntoViewIfNeeded();
    await panel.screenshot({ path: path.join(root, 'artifacts', 'companion-memories.png') });
    await panel.locator('#sound-settings summary').click();
    await pet.screenshot({ path: path.join(root, 'artifacts', 'pet.png'), omitBackground: true });
    await panel.locator('#collapse').click();
    const hidden = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isVisible());
    assert.equal(hidden, false);
    await panel.waitForTimeout(1800);
    const audible = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).webContents.isCurrentlyAudible());
    assert.equal(audible, true, 'hidden panel continues producing audio');
    const running = await panel.evaluate(() => window.mori.getState());
    assert.equal(running.timer.running, true);
    assert.ok(running.timer.remaining < 1500000);
    await app.evaluate(({ powerMonitor }) => powerMonitor.emit('suspend'));
    const paused = await panel.evaluate(() => window.mori.getState());
    assert.equal(paused.timer.running, false);
    await app.evaluate(({ powerMonitor }) => powerMonitor.emit('resume'));
    await panel.waitForTimeout(500);
    assert.equal((await panel.evaluate(() => window.mori.getState())).timer.remaining, paused.timer.remaining);
    await panel.evaluate(() => window.mori.windowAction('toggle'));
    await panel.locator('#music-source').selectOption('local');
    await panel.waitForFunction(() => document.querySelector('#music-title').textContent === 'local-tone.wav' && document.querySelector('#music-toggle').getAttribute('aria-pressed') === 'true');
    // Disable rain so the local file must be the audible source.
    await panel.locator('#rain-toggle').click();
    await panel.waitForTimeout(500);
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).webContents.isCurrentlyAudible()), true);
    await panel.locator('#music-toggle').click();
    const initialSize = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('pet.html')).getBounds());
    for (let i = 0; i < 6; i++) {
      await pet.evaluate(() => { window.mori.drag('begin'); window.mori.drag('move'); window.mori.drag('end'); });
    }
    await pet.waitForTimeout(200);
    const afterDrags = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('pet.html')).getBounds());
    assert.ok(Math.abs(afterDrags.height - initialSize.height) <= 2, `dragging must not grow the window: ${initialSize.height} -> ${afterDrags.height}`);
    const native = await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().map(w => ({ title: w.getTitle(), top: w.isAlwaysOnTop(), background: w.getBackgroundColor(), bounds: w.getBounds() })));
    assert.equal(native.find(w => w.title.includes('桌寵')).top, true);
    assert.equal(native.find(w => w.title.includes('專注小屋')).top, false);
    await panel.locator('#mode-focus').click();
    await panel.locator('#reset').click();
    await panel.locator('#quick-start').click();
    const quick = await panel.evaluate(() => window.mori.getState());
    assert.equal(quick.timer.duration, 300000);
    assert.equal(quick.settings.focus, 25);
    await panel.locator('#music-toggle').click();
    await panel.locator('#rain-toggle').click();
    await panel.waitForFunction(() => document.querySelector('#music-toggle').getAttribute('aria-pressed') === 'true' && document.querySelector('#rain-toggle').getAttribute('aria-pressed') === 'true');
    await panel.locator('#finish-day').click();
    assert.equal((await panel.evaluate(() => window.mori.getState())).timer.running, false);
    assert.equal(await panel.locator('#music-toggle').getAttribute('aria-pressed'), 'false');
    assert.equal(await panel.locator('#rain-toggle').getAttribute('aria-pressed'), 'false');
    await panel.locator('#presence').selectOption('quiet');
    await panel.locator('#pin-panel').click();
    assert.deepEqual(errors, []);
    await app.close();
    app = null;
    const saved = JSON.parse(fs.readFileSync(path.join(dataDir, 'state.json'), 'utf8'));
    assert.equal(saved.tasks[0].title, '整理今天的靈感');
    assert.equal(saved.timer.running, false);
    assert.equal(saved.settings.musicSource, 'local');
    // A moved file must show an error after restart and allow fallback to built-in music.
    fs.renameSync(waveFile, path.join(dataDir, 'moved-tone.wav'));
    app = await electron.launch(launchOptions);
    const reopenedPet = await findPage(app, 'pet.html');
    await reopenedPet.waitForSelector('#pet');
    await reopenedPet.waitForFunction(() => document.querySelector('#pet').dataset.ready === 'true');
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('pet.html')).isVisible()), false, 'restart preserves quiet mode');
    await reopenedPet.evaluate(() => window.mori.windowAction('toggle'));
    const reopened = await findPage(app, 'panel.html');
    await reopened.waitForSelector('#start');
    await reopened.evaluate(async () => { await window.mori.act('companionSettings', { key: 'guideSeen', value: true }); document.querySelector('#guide-dialog')?.close(); });
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isAlwaysOnTop()), true, 'restart preserves pinning');
    await reopened.locator('#presence').selectOption('companion');
    assert.equal(await reopened.locator('#memories .unlocked').count(), 1);
    await reopened.locator('#sound-settings summary').click();
    assert.equal((await reopened.evaluate(() => window.mori.getState())).timer.running, false);
    assert.equal(await reopened.locator('#music-source').inputValue(), 'local');
    assert.equal(await reopened.locator('#background-source').inputValue(), 'ocean');
    assert.equal(await reopened.locator('#rain-toggle').getAttribute('aria-pressed'), 'false');
    assert.equal(await reopened.locator('#music-toggle').getAttribute('aria-pressed'), 'false');
    await reopened.locator('#music-toggle').click();
    await reopened.waitForFunction(() => document.querySelector('#error').textContent.includes('找不到'));
    await reopened.locator('#music-source').selectOption('builtin');
    await reopened.locator('#music-toggle').click();
    await reopened.waitForFunction(() => document.querySelector('#music-toggle').getAttribute('aria-pressed') === 'true');
    await reopened.locator('#collapse').click();
    await reopenedPet.route('**/mori-reading-atlas.png', route => route.abort());
    await reopenedPet.reload();
    await reopenedPet.waitForFunction(() => document.querySelector('#pet').dataset.ready === 'true');
    assert.equal(await reopenedPet.locator('#pet').getAttribute('data-reading-ready'), 'false', 'optional expressions failing must preserve the base character');
    await reopenedPet.route('**/mori-catgirl-atlas.png', route => route.abort());
    await reopenedPet.reload();
    await reopenedPet.waitForFunction(() => document.querySelector('#pet').dataset.ready === 'error');
    await reopenedPet.locator('#tools').click();
    assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('panel.html')).isVisible()), true, 'tools remain accessible when character loading fails');
    await app.close(); app = null;
    fs.writeFileSync(path.join(root, 'artifacts', process.env.SMOKE_PACKAGED ? 'packaged-smoke-results.json' : 'smoke-results.json'), JSON.stringify({ passed: true, native, errors, dataDir, localMusic: true, restartAndMissingFileRecovery: true, catgirl: { singleClick: true, doubleClick: true, seatedHeadPat: true, heldAndDrop: true, pointerCancel: true, readingBlink: true, crouchTransition: true, reducedMotion: true, alphaHit: true, imageFailureFallback: true, optionalAtlasFallback: true } }, null, 2));
    console.log('PASS: catgirl alpha/single-double click/head-pat/drag/cancel/focus/fallback; timer, hidden audio, persistence, local music and restart recovery.');
  } finally {
    if (app) await app.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
